// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeSheetSystem.Data.Data;

#nullable disable

namespace TimeSheetSystem.Data.Migrations
{
    [DbContext(typeof(TimeSheetDbContext))]
    partial class TimeSheetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TimeSheetSystem")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "EmployeeId")
                        .HasName("EmployeeRole_pkey");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeRole", "TimeSheetSystem");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("Employee_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "Email" }, "Employee_Email_key")
                        .IsUnique();

                    b.ToTable("Employee", "TimeSheetSystem");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.EmployeeProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("EmployeeProject_pkey");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("EmployeeProject", "TimeSheetSystem");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("Manager")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxEmployees")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("Project_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Manager");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Project", "TimeSheetSystem");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Role_pkey");

                    b.HasIndex(new[] { "Name" }, "Role_Name_key")
                        .IsUnique();

                    b.ToTable("Role", "TimeSheetSystem");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.TimeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("TimeLog_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TimeLog", "TimeSheetSystem");
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.HasOne("TimeSheetSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("EmployeeRole_EmployeeId_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("EmployeeRole_RoleId_fkey");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Employee", b =>
                {
                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("Employee_CreatedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "DeletedByNavigation")
                        .WithMany("InverseDeletedByNavigation")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("Employee_DeletedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "UpdatedByNavigation")
                        .WithMany("InverseUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("Employee_UpdatedBy_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.EmployeeProject", b =>
                {
                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "AssignedByNavigation")
                        .WithMany("EmployeeProjectAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .IsRequired()
                        .HasConstraintName("EmployeeProject_AssignedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "CreatedByNavigation")
                        .WithMany("EmployeeProjectCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("EmployeeProject_CreatedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "DeletedByNavigation")
                        .WithMany("EmployeeProjectDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("EmployeeProject_DeletedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "Employee")
                        .WithMany("EmployeeProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("EmployeeProject_EmployeeId_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("EmployeeProject_ProjectId_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "UpdatedByNavigation")
                        .WithMany("EmployeeProjectUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("EmployeeProject_UpdatedBy_fkey");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Project", b =>
                {
                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "CreatedByNavigation")
                        .WithMany("ProjectCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("Project_CreatedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "DeletedByNavigation")
                        .WithMany("ProjectDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("Project_DeletedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "ManagerNavigation")
                        .WithMany("ProjectManagerNavigations")
                        .HasForeignKey("Manager")
                        .IsRequired()
                        .HasConstraintName("Project_Manager_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "UpdatedByNavigation")
                        .WithMany("ProjectUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("Project_UpdatedBy_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("ManagerNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.TimeLog", b =>
                {
                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "ApprovedByNavigation")
                        .WithMany("TimeLogApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("TimeLog_ApprovedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "CreatedByNavigation")
                        .WithMany("TimeLogCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("TimeLog_CreatedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "DeletedByNavigation")
                        .WithMany("TimeLogDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("TimeLog_DeletedBy_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "Employee")
                        .WithMany("TimeLogEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("TimeLog_EmployeeId_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Project", "Project")
                        .WithMany("TimeLogs")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("TimeLog_ProjectId_fkey");

                    b.HasOne("TimeSheetSystem.Data.Models.Employee", "UpdatedByNavigation")
                        .WithMany("TimeLogUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("TimeLog_UpdatedBy_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Employee", b =>
                {
                    b.Navigation("EmployeeProjectAssignedByNavigations");

                    b.Navigation("EmployeeProjectCreatedByNavigations");

                    b.Navigation("EmployeeProjectDeletedByNavigations");

                    b.Navigation("EmployeeProjectEmployees");

                    b.Navigation("EmployeeProjectUpdatedByNavigations");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseDeletedByNavigation");

                    b.Navigation("InverseUpdatedByNavigation");

                    b.Navigation("ProjectCreatedByNavigations");

                    b.Navigation("ProjectDeletedByNavigations");

                    b.Navigation("ProjectManagerNavigations");

                    b.Navigation("ProjectUpdatedByNavigations");

                    b.Navigation("TimeLogApprovedByNavigations");

                    b.Navigation("TimeLogCreatedByNavigations");

                    b.Navigation("TimeLogDeletedByNavigations");

                    b.Navigation("TimeLogEmployees");

                    b.Navigation("TimeLogUpdatedByNavigations");
                });

            modelBuilder.Entity("TimeSheetSystem.Data.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");

                    b.Navigation("TimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
